- name: ROLE COMPOSER
  hosts: all
  become: yes
  remote_user: root

  tasks:
    - name: INSTALL composer
      apt:
        name: ['composer']

    - name: EXPORT composer
      command: echo "export PATH=$PATH:~/.config/composer/vendor/bin" >> ~/.bashrc
