- name: Backend Playbook
  hosts: all

- import_playbook: roles/base/tasks/main.yml

- import_playbook: roles/php/tasks/main.yml

- import_playbook: roles/composer/tasks/main.yml

- import_playbook: roles/laravel/tasks/main.yml

- import_playbook: roles/build_app/tasks/main.yml

- import_playbook: roles/apache2/tasks/main.yml
